[package]
name = "console-draw"
version = "0.1.0"
edition = "2021"

[dependencies]
drm = "0.14"
orbclient.workspace = true
ransid = "0.4"

graphics-ipc = { path = "../graphics-ipc" }

[features]
default = []
