[package]
name = "graphics-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
libredox = "0.1.3"
redox-ioctl = { git = "https://gitlab.redox-os.org/Ibuki.O/relibc.git", branch = "replace-unlink-rmdir-with-unlinkat" }
redox_syscall = "0.6"

common = { path = "../../common" }
