[package]
name = "graphics-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
drm = "0.14"
log.workspace = true
libredox.workspace = true
redox-ioctl.workspace = true
redox_syscall.workspace = true

common = { path = "../../common" }
