[package]
name = "graphics-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
libredox = "0.1.3"
redox_syscall = "0.5"
redox-ioctl = { git = "https://gitlab.redox-os.org/redox-os/relibc.git" }

common = { path = "../../common" }
