[[drivers]]
name = "Intel HD Graphics"
class = 0x03
ids = { 0x8086 = [
    # Kaby Lake from Volume 4: Configurations in
    # https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/kaby-lake.html
    0x5912,
    0x5916,
    0x591B,
    0x591E,
    0x5926,
    # Comet Lake from Volume 1: Configurations in
    # https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/comet-lake.html
    0x9B21,
    0x9B41,
    0x9BA4,
    0x9BAA,
    0x9BAC,
    0x9BC4,
    0x9BC5,
    0x9BC6,
    0x9BC8,
    0x9BCA,
    0x9BCC,
    0x9BE6,
    0x9BF6,
    # Tiger Lake Mobile from Volume 4: Configurations in
    # https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/tiger-lake.html
    0x9A40,
    0x9A49,
    0x9A60,
    0x9A68,
    0x9A70,
    0x9A78,
    # Alchemist from Volume 4: Configurations in
    # https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/alchemist-arctic-sound-m.html
    0x5690, # A770M
    0x5691, # A730M
    0x5692, # A550M
    0x5693, # A370M
    0x5694, # A350M
    0x5696, # A570M
    0x5697, # A530M
    0x56A0, # A770
    0x56A1, # A750
    0x56A5, # A380
    0x56A6, # A310
    0x56B0, # Pro A30M
    0x56B1, # Pro A40/A50
    0x56B2, # Pro A60M
    0x56B3, # Pro A60
    0x56C0, # GPU Flex 170
    0x56C1, # GPU Flex 140
] }
command = ["ihdgd"]
