[package]
name = "nvmed"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7"
bitflags = "2"
futures = "0.3"
libredox.workspace = true
log.workspace = true
parking_lot = "0.12.1"
redox_event.workspace = true
redox_syscall = { workspace = true, features = ["std"] }
smallvec = "1"

executor = { path = "../../executor" }
common = { path = "../../common" }
daemon = { path = "../../../daemon" }
driver-block = { path = "../driver-block" }
partitionlib = { path = "../partitionlib" }
pcid = { path = "../../pcid" }

[features]
default = []
