[package]
name = "rtl8168d"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "2"
libredox.workspace = true
log.workspace = true
redox_event.workspace = true
redox_syscall.workspace = true

common = { path = "../../common" }
daemon = { path = "../../../daemon" }
driver-network = { path = "../driver-network" }
pcid = { path = "../../pcid" }
