[package]
name = "rtl8168d"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "2"
libredox = "0.1.11"
log = "0.4"
redox_event = "0.4.2"
redox_syscall = "0.6"

common = { path = "../../common" }
daemon = { path = "../../../daemon" }
driver-network = { path = "../driver-network" }
pcid = { path = "../../pcid" }
