[package]
name = "randd"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_chacha = "0.2"
rand_core = "0.5"
daemon = { path = "../daemon" }
redox_syscall = "0.6"
libredox = "0.1.3"
sha2 = "0.8"
redox-scheme = "0.8.3"

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "11.0.1"
