[package]
name = "driver-network"
version = "0.1.0"
edition = "2021"

[dependencies]
libredox = "0.1.3"
daemon = { path = "../../../daemon" }
redox-scheme = "0.4"
redox_syscall = { version = "0.5", features = ["std"] }
