[package]
name = "driver-network"
version = "0.1.0"
edition = "2021"

[dependencies]
libredox.workspace = true
daemon = { path = "../../../daemon" }
redox-scheme.workspace = true
redox_syscall = { workspace = true, features = ["std"] }
