[package]
name = "zerod"
version = "0.1.0"
authors = ["Alex Lyon <arcterus@mail.com>"]
edition = "2021"

[dependencies]
redox_syscall.workspace = true
redox-scheme.workspace = true
daemon = { path = "../daemon" }
libredox.workspace = true
