[package]
name = "alxd"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "2"
redox_event.workspace = true
redox_syscall.workspace = true

common = { path = "../../common" }
daemon = { path = "../../../daemon" }
libredox.workspace = true
redox-scheme.workspace = true
