[package]
name = "alxd"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "2"
redox_event = "0.4.1"
redox_syscall = "0.5"

common = { path = "../../common" }
daemon = { path = "../../../daemon" }
libredox = "0.1.3"
redox-scheme = "0.8.2"
