[package]
name = "vboxd"
version = "0.1.0"
edition = "2018"

[dependencies]
libredox = "0.1.3"
orbclient = "0.3.47"
redox_event = "0.4.1"
redox_syscall = "0.5"

common = { path = "../common" }
daemon = { path = "../../daemon" }
pcid = { path = "../pcid" }
