[package]
name = "virtio-netd"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
static_assertions = "1.1.0"
futures = { version = "0.3.28", features = ["executor"] }

virtio-core = { path = "../../virtio-core" }
pcid = { path = "../../pcid" }
common = { path = "../../common" }
daemon = { path = "../../../daemon" }
driver-network = { path = "../driver-network" }

redox_syscall.workspace = true
libredox.workspace = true
