[package]
name = "ptyd"
version = "0.1.0"
edition = "2021"

[dependencies]
libredox = "0.1.3"
daemon = { path = "../daemon" }
redox-scheme = "0.8.2"
redox_event = "0.4.0"
redox_syscall = "0.5.0"
redox_termios = "0.1.3"
