[package]
name = "ptyd"
version = "0.1.0"
edition = "2021"

[dependencies]
libredox.workspace = true
daemon = { path = "../daemon" }
redox-scheme.workspace = true
redox_event.workspace = true
redox_syscall.workspace = true
redox_termios.workspace = true
