[package]
name = "executor"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Async framework for queue-based HW interfaces"

[dependencies]
log.workspace = true
redox_event.workspace = true
slab = "0.4.9"
